version: 2
jobs:
  build-content-job:
    docker:
      - image: circleci/python:3.6.2
    working_directory: /tmp/blog
    steps:
      - checkout

      - run:
          name: Create workspace directory
          command: |
            mkdir -p /tmp/workspace/published

      - restore_cache:
          name: Restore Python virtual environment cache
          keys:
          - v1-venv-{{ .Branch }}-{{ checksum "./requirements.txt" }}-
          - v1-venv-{{ .Branch }}-
          - v1-venv-

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv /tmp/venv
            source /tmp/venv/bin/activate
            pip install --no-input --compile --exists-action=a --use-wheel --upgrade wheel setuptools awscli invoke

      - run:
          name: Install dependencies
          command: |
            source /tmp/venv/bin/activate
            pip install --no-input --compile --exists-action=a --use-wheel -r ./requirements.txt

      - run:
          name: Build Pelican content
          command: |
            source /tmp/venv/bin/activate
            pelican -s publishconf.py -o /tmp/workspace/published/

      - save_cache:
          paths:
            - /tmp/venv/
          key: v1-venv-{{ .Branch }}-{{ checksum "./requirements.txt" }}-{{ epoch }}

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - published

  build-theme-job:
    working_directory: /tmp/workspace/
    docker:
      - image: node:9

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-
          - v1-dependencies-{{ .Branch }}-
          - v1-dependencies-

      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Build Pelican content
          command: |
            yarn add gulp@next
            yarn add bower
            yarn install --production=false --check-files --pure-lockfile --network-concurrency=32 --non-interactive

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-{{ epoch }}

      - run:
          name: Install dependencies
          command: |
            node_modules/.bin/bower install --config.interactive=false --allow-root
            node_modules/.bin/gulp less --production
            node_modules/.bin/gulp minify

      - run:
          name: Install dependencies
          command: |
            node_modules/.bin/gulp js --production
            node_modules/.bin/gulp less --production
            node_modules/.bin/gulp minify

      - run:
          name: Install dependencies
          command: |
            # Ref: https://unix.stackexchange.com/questions/34549/how-to-rename-multiple-files-by-removing-the-extension#comment46942_34578
            for i in ./*.html; do mv -i "$i" "${i%.html}"; done

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - published

  deploy-job:
    docker:
      - image: circleci/python:3.6.2
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - restore_cache:
          name: Restore Python virtual environment cache
          keys:
          - v1-venv2-{{ .Branch }}-
          - v1-venv2-

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv /tmp/venv
            source /tmp/venv/bin/activate
            pip install --no-input --compile --exists-action=a --use-wheel --upgrade awscli

      - save_cache:
          paths:
            - /tmp/venv/
          key: v1-venv2-{{ .Branch }}-{{ epoch }

      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            source /tmp/venv/bin/activate

            aws s3 sync /tmp/workspace/published s3://blog-vaclavdohnal-cz/ --delete
            aws s3 cp --include "*" \
                      --content-type="text/html" \
                      --metadata-directive="REPLACE" \
                      --recursive s3://blog-vaclavdohnal-cz/posts/ s3://blog-vaclavdohnal-cz/posts/

            aws cloudfront create-invalidation --distribution-id E2VB5N973KQCN5 --paths '/*'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-content-job
      - build-theme-job:
          requires:
            - build-content-job
      - deploy-job:
          requires:
            - build-theme-job
          filters:
            branches:
              only: master
